# Generated by Django 5.1.6 on 2025-03-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_body_book_author_book_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='banner',
            field=models.ImageField(blank=True, default='default_book.jpg', upload_to='banners/'),
        ),
    ]
